[package]
name = "chain-rs"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
chain-rs-lib = { path = "lib", features = ["serde"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
